# Generated by Django 4.2.7 on 2024-06-12 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flat_number', models.PositiveIntegerField(verbose_name='номер квартиры')),
                ('area', models.FloatField(verbose_name='площадь квартиры')),
            ],
            options={
                'verbose_name': 'квартира',
                'verbose_name_plural': 'квартиры',
            },
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_number', models.PositiveIntegerField(verbose_name='номер дома')),
                ('town', models.CharField(max_length=30, verbose_name='город')),
                ('street', models.TextField(max_length=100, verbose_name='улица')),
            ],
            options={
                'verbose_name': 'дом',
                'verbose_name_plural': 'дома',
            },
        ),
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(choices=[('Стоимость 1м3 холодной воды', 'Стоимость 1м3 холодной воды'), ('Стоимость 1м3 горячей воды', 'Стоимость 1м3 горячей воды'), ('Содержание общего имущества за 1м2', 'Содержание общего имущества за 1м2')], max_length=255, verbose_name='название услуги')),
                ('price_per_unit', models.FloatField(verbose_name='цена за единицу')),
                ('unit_of_measure', models.CharField(max_length=50, verbose_name='единица измерения')),
            ],
            options={
                'verbose_name': 'Тариф',
                'verbose_name_plural': 'Тарифы',
            },
        ),
        migrations.CreateModel(
            name='Water_Meter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.PositiveIntegerField(verbose_name='серийный номер')),
                ('mount', models.CharField(choices=[('january', 'январь'), ('february', 'февраль'), ('march', 'март'), ('april', 'май'), ('may', 'май'), ('june', 'июнь'), ('july', 'июль'), ('august', 'август'), ('september', 'сентябрь'), ('october', 'октябрь'), ('ноябрь', 'November'), ('december', 'сентябрь')], max_length=20, verbose_name='месяц')),
                ('year', models.CharField(choices=[('2023', '2023'), ('2024', '2024'), ('2025', '2025')], max_length=4, verbose_name='год')),
                ('data_cold', models.FloatField(blank=True, null=True, verbose_name='показания холодной воды')),
                ('data_hot', models.FloatField(blank=True, null=True, verbose_name='показания теплой воды')),
                ('float_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hcs.flat', verbose_name='номер квартира')),
            ],
        ),
        migrations.AddField(
            model_name='flat',
            name='home',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hcs.home', verbose_name='номер дома'),
        ),
    ]
