# Generated by Django 4.2.7 on 2024-06-12 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hcs', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='home',
            unique_together={('town', 'street', 'house_number')},
        ),
    ]
