# Generated by Django 4.2.7 on 2024-06-12 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hcs', '0003_alter_water_meter_options_alter_flat_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='water_meter',
            old_name='float_number',
            new_name='flat',
        ),
    ]
