# Generated by Django 4.2.7 on 2024-06-12 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hcs', '0005_remove_water_meter_data_cold_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tariff',
            name='unit_of_measure',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='единица измерения'),
        ),
        migrations.AlterField(
            model_name='water_meter',
            name='data',
            field=models.FloatField(verbose_name='количество м3 за месяц'),
        ),
    ]
