# Generated by Django 4.2.7 on 2024-06-12 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hcs', '0006_alter_tariff_unit_of_measure_alter_water_meter_data'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tariff',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='tariff',
            name='unit_of_measure',
        ),
    ]
