# Generated by Django 4.2.7 on 2024-06-12 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hcs', '0007_alter_tariff_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='water_meter',
            name='data',
        ),
        migrations.AddField(
            model_name='water_meter',
            name='actual_tariff',
            field=models.FloatField(blank=True, null=True, verbose_name='актуальный тариф на месяц'),
        ),
        migrations.AddField(
            model_name='water_meter',
            name='data_meter',
            field=models.FloatField(default=0, verbose_name='данные счетчика в текущем месяце'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='water_meter',
            name='price',
            field=models.FloatField(blank=True, null=True, verbose_name='стоимость за объем'),
        ),
        migrations.AddField(
            model_name='water_meter',
            name='volume',
            field=models.FloatField(blank=True, null=True, verbose_name='объем воды за месяц'),
        ),
    ]
