# Generated by Django 4.2.7 on 2024-06-13 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hcs', '0008_remove_water_meter_data_water_meter_actual_tariff_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='water_meter',
            old_name='mount',
            new_name='month',
        ),
    ]
