# Generated by Django 4.2.7 on 2024-06-15 17:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hcs', '0011_alter_servicerendered_month_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicerendered',
            name='actual_tariff_price',
        ),
        migrations.RemoveField(
            model_name='servicerendered',
            name='month',
        ),
        migrations.RemoveField(
            model_name='servicerendered',
            name='year',
        ),
        migrations.RemoveField(
            model_name='water_meter',
            name='month',
        ),
        migrations.RemoveField(
            model_name='water_meter',
            name='year',
        ),
        migrations.AddField(
            model_name='servicerendered',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default='2024-06-15T17:04:32Z', verbose_name='дата и время формирования услуги'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tariff',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default='2024-06-15T17:04:32', verbose_name='дата создания тарифа'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='water_meter',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='дата и время показаний'),
            preserve_default=False,
        ),
    ]
