# Generated by Django 4.2.7 on 2024-06-15 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hcs', '0012_remove_servicerendered_actual_tariff_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerendered',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='дата и время формирования услуги'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='дата создания тарифа'),
        ),
        migrations.AlterField(
            model_name='water_meter',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='дата и время показаний'),
        ),
    ]
