# Generated by Django 4.2.7 on 2024-06-15 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hcs', '0014_alter_servicerendered_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='area',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='площадь квартиры'),
        ),
        migrations.AlterField(
            model_name='water_meter',
            name='data_meter',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='данные счетчика в текущем месяце'),
        ),
    ]
