# Generated by Django 4.2.7 on 2024-06-15 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hcs', '0015_alter_flat_area_alter_water_meter_data_meter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='area',
            field=models.FloatField(verbose_name='площадь квартиры'),
        ),
        migrations.AlterField(
            model_name='servicerendered',
            name='price',
            field=models.FloatField(blank=True, null=True, verbose_name='стоимость за объем'),
        ),
        migrations.AlterField(
            model_name='servicerendered',
            name='volume',
            field=models.FloatField(blank=True, null=True, verbose_name='объем воды за месяц'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='price_per_unit',
            field=models.FloatField(verbose_name='цена за единицу'),
        ),
        migrations.AlterField(
            model_name='water_meter',
            name='data_meter',
            field=models.FloatField(verbose_name='данные счетчика в текущем месяце'),
        ),
    ]
