# Generated by Django 4.2.7 on 2024-06-16 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hcs', '0016_alter_flat_area_alter_servicerendered_price_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Home',
            new_name='House',
        ),
        migrations.RenameField(
            model_name='flat',
            old_name='home',
            new_name='house',
        ),
        migrations.RenameField(
            model_name='house',
            old_name='home_number',
            new_name='house_number',
        ),
        migrations.AlterUniqueTogether(
            name='flat',
            unique_together={('house', 'flat_number')},
        ),
        migrations.AlterUniqueTogether(
            name='house',
            unique_together={('town', 'street', 'house_number')},
        ),
    ]
